//TAB 1 STACK NAVIGATOR
export const STARGATE_HOME = 'STARGATE_HOME';
export const STARGATE_DETAILS = 'STARGATE_DETAILS';
//TAB 2  TAB NAVIGATOR
export const BATMAN_HOME = 'BATMAN_HOME';
export const BATMAN_DETAILS = 'BATMAN_DETAILS';
//TAB 3 DRAWER NAVIGATOR
export const SPIDER_HOME = 'SPIDER_HOME';
export const SPIDER_DETAILS = 'SPIDER_DETAILS';
